# Importar Librerías a utilizar

In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# Split Test-Train-Validation

In [2]:
df = pd.read_csv('/home/bryan/Escritorio/Paper/Prueba1/HB.csv')

In [3]:
df.head()

,Unnamed: 0,-X1-,-Y1-,-Z1-,-X2-,-Y2-,-Z2-,-X3-,-Y3-,-Z3-,...,-Z5-,-X6-,-Y6-,-Z6-,-X7-,-Y7-,-Z7-,-X8-,-Y8-,-Z8-
0,0,0.000213,0.000274,0.000279,0.000146,0.000231,0.000176,0.000063,0.000208,0.000323,...,0.000395,0.000267,0.000030,0.000054,0.000262,0.000176,0.000132,0.000139,0.000058,-0.000016
1,1,0.000192,0.000265,0.000262,0.000148,0.000194,0.000173,0.000118,0.000175,0.000318,...,0.000399,0.000244,0.000066,0.000108,0.000247,0.000111,0.000165,0.000150,0.000048,0.000020
2,2,0.000175,0.000227,0.000212,0.000202,0.000195,0.000169,0.000127,0.000208,0.000320,...,0.000396,0.000161,0.000048,0.000026,0.000167,0.000172,0.000110,0.000103,0.000073,-0.000025
3,3,0.000185,0.000281,0.000237,0.000158,0.000218,0.000192,0.000154,0.000250,0.000319,...,0.000370,0.000256,0.000077,0.000074,0.000219,0.000191,0.000155,0.000153,0.000055,-0.000054
4,4,0.000185,0.000275,0.000246,0.000178,0.000225,0.000167,0.000139,0.000250,0.000345,...,0.000389,0.000321,0.000061,0.000111,0.000241,0.000171,0.000142,0.000181,0.000032,0.000016

In [4]:
X_train, x_tv = train_test_split(df, test_size=0.30, shuffle=False)

In [5]:
x_test, x_val = train_test_split(x_tv.iloc[:,1:], test_size=0.10, shuffle=False)

In [18]:
X_train.iloc[:,1:].to_csv('/home/bryan/Escritorio/Paper/Entrenamiento/Train.csv')
x_test.to_csv('/home/bryan/Escritorio/Paper/Entrenamiento/Test.csv')
x_val.to_csv('/home/bryan/Escritorio/Paper/Entrenamiento/Val.csv')

# Reescalar

In [2]:
train = pd.read_csv('/home/bryan/Escritorio/Paper/Entrenamiento/Train.csv').iloc[:,1:]

In [3]:
train.head()

,-X1-,-Y1-,-Z1-,-X2-,-Y2-,-Z2-,-X3-,-Y3-,-Z3-,-X4-,...,-Z5-,-X6-,-Y6-,-Z6-,-X7-,-Y7-,-Z7-,-X8-,-Y8-,-Z8-
0,0.000213,0.000274,0.000279,0.000146,0.000231,0.000176,0.000063,0.000208,0.000323,0.000154,...,0.000395,0.000267,0.000030,0.000054,0.000262,0.000176,0.000132,0.000139,0.000058,-0.000016
1,0.000192,0.000265,0.000262,0.000148,0.000194,0.000173,0.000118,0.000175,0.000318,0.000143,...,0.000399,0.000244,0.000066,0.000108,0.000247,0.000111,0.000165,0.000150,0.000048,0.000020
2,0.000175,0.000227,0.000212,0.000202,0.000195,0.000169,0.000127,0.000208,0.000320,0.000144,...,0.000396,0.000161,0.000048,0.000026,0.000167,0.000172,0.000110,0.000103,0.000073,-0.000025
3,0.000185,0.000281,0.000237,0.000158,0.000218,0.000192,0.000154,0.000250,0.000319,0.000093,...,0.000370,0.000256,0.000077,0.000074,0.000219,0.000191,0.000155,0.000153,0.000055,-0.000054
4,0.000185,0.000275,0.000246,0.000178,0.000225,0.000167,0.000139,0.000250,0.000345,0.000229,...,0.000389,0.000321,0.000061,0.000111,0.000241,0.000171,0.000142,0.000181,0.000032,0.000016

In [4]:
scaler = MinMaxScaler()

In [5]:
scaled_train = scaler.fit_transform(train)

In [6]:
test = pd.read_csv('/home/bryan/Escritorio/Paper/Entrenamiento/Test.csv').iloc[:,1:]

In [7]:
scaled_test = scaler.fit_transform(test)

In [8]:
val = pd.read_csv('/home/bryan/Escritorio/Paper/Entrenamiento/Val.csv').iloc[:,1:]

In [9]:
scaled_val = scaler.fit_transform(val)

### Guardar lo reescalado

In [10]:
def cols_exp():
    index_ex = []
    for sensor in range(1,9):
            index_ex.append('-X'+str(sensor)+'-')
            index_ex.append('-Y'+str(sensor)+'-')
            index_ex.append('-Z'+str(sensor)+'-')
    return index_ex

In [11]:
df_t = pd.DataFrame(scaled_train, columns = cols_exp()).to_csv('/home/bryan/Escritorio/Paper/Reescalado/Train.csv')
df_ts = pd.DataFrame(scaled_test, columns = cols_exp()).to_csv('/home/bryan/Escritorio/Paper/Reescalado/Test.csv')
df_v = pd.DataFrame(scaled_val, columns = cols_exp()).to_csv('/home/bryan/Escritorio/Paper/Reescalado/Val.csv')